<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Pug.Sqetch.ProjectInfoStore</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Pug.Sqetch.Models\Pug.Sqetch.Models.csproj" />
    </ItemGroup>

</Project>