<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Sqetch</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Pug.Sqetch.Abstractions\Pug.Sqetch.Abstractions.csproj" />
      <ProjectReference Include="..\Pug.Sqetch.Models\Pug.Sqetch.Models.csproj" />
      <ProjectReference Include="..\Pug.Sqetch.ProjectInfoStore.Abstractions\Pug.Sqetch.ProjectInfoStore.Abstractions.csproj" />
    </ItemGroup>

</Project>
