<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Plan.cs" />
      <Compile Remove="FileSystemProjectInfoStore\**" />
      <Compile Remove="JsonFileObjectRepository\**" />
      <Compile Remove="Abstractions\ObjectRepository\**" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Abstractions\" />
      <Folder Include="Cli\" />
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="FileSystemProjectInfoStore\**" />
      <EmbeddedResource Remove="JsonFileObjectRepository\**" />
      <EmbeddedResource Remove="Abstractions\ObjectRepository\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="FileSystemProjectInfoStore\**" />
      <None Remove="JsonFileObjectRepository\**" />
      <None Remove="Abstractions\ObjectRepository\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sqetch.Common\Sqetch.Common.csproj" />
      <ProjectReference Include="..\Sqetch.Models\Sqetch.Models.csproj" />
    </ItemGroup>

</Project>
